#!/bin/bash
# ================================================================
# Properly — Local Setup Script
# Run this ONCE after unzipping the project:
#   chmod +x setup.sh && ./setup.sh
# ================================================================

set -e  # Exit on any error

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Colour

echo ""
echo -e "${CYAN}🦉 Properly — Local Setup${NC}"
echo "================================"
echo ""

# ── CHECK NODE VERSION ──────────────────────────────────────────
echo -e "${BLUE}[1/5] Checking Node.js version...${NC}"
NODE_VER=$(node --version 2>/dev/null | sed 's/v//' | cut -d. -f1)
if [ -z "$NODE_VER" ]; then
  echo -e "${RED}✗ Node.js not found!${NC}"
  echo "  Install from: https://nodejs.org (version 20 recommended)"
  exit 1
fi
if [ "$NODE_VER" -lt 22 ]; then
  echo -e "${RED}✗ Node.js v${NODE_VER} is too old. Need v22+ for built-in SQLite${NC}"
  echo "  Download Node.js v22 LTS from: https://nodejs.org"
  exit 1
fi
echo -e "${GREEN}✓ Node.js v$(node --version) found${NC}"

# ── INSTALL BACKEND DEPS ────────────────────────────────────────
echo ""
echo -e "${BLUE}[2/5] Installing backend dependencies...${NC}"
cd backend && npm install --silent
echo -e "${GREEN}✓ Backend packages installed${NC}"
cd ..

# ── INSTALL FRONTEND DEPS ───────────────────────────────────────
echo ""
echo -e "${BLUE}[3/5] Installing frontend dependencies...${NC}"
cd frontend && npm install --silent
echo -e "${GREEN}✓ Frontend packages installed${NC}"
cd ..

# ── CREATE BACKEND .env ─────────────────────────────────────────
echo ""
echo -e "${BLUE}[4/5] Creating backend/.env ...${NC}"

if [ -f "backend/.env" ]; then
  echo -e "${YELLOW}⚠  backend/.env already exists — skipping (delete it to reset)${NC}"
else
  cat > backend/.env << 'ENVEOF'
# Properly — Local Development Environment
# Generated by setup.sh — safe to edit

NODE_ENV=development
PORT=3001

# Database — stored locally in backend/data/properly.db
DB_PATH=./data/properly.db

# JWT — this is fine for local dev; change for production
JWT_SECRET=local-dev-secret-not-for-production-32chars
JWT_EXPIRES_IN=7d

# CORS — Vite dev server
CORS_ORIGINS=http://localhost:5173,http://localhost:4173

# Rate limiting
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX=500

# ── OPTIONAL: Add your AI/speech keys below ───────────────────
# The app works WITHOUT these (uses fallbacks)
# but adding them unlocks the full experience.

# Google Gemini Flash — FREE (1,500 req/day, no billing)
# Get key: https://aistudio.google.com/app/apikey
GEMINI_API_KEY=

# Groq (Llama 3.1) — optional premium (Mrs. Owl coaching)
# Get key: https://console.groq.com/keys
GROQ_API_KEY=

# Azure Speech — FREE F0 (pronunciation scoring + TTS)
# Setup: https://portal.azure.com → Create resource → Speech → Free F0
AZURE_SPEECH_KEY=
AZURE_SPEECH_REGION=uksouth

# Email verification (optional — app works without it)
# Gmail: enable 2FA, then create App Password at myaccount.google.com
SMTP_PROVIDER=gmail
SMTP_USER=your.email@gmail.com
SMTP_PASS=your-16-char-app-password
SMTP_FROM_NAME=Properly Phonics
APP_URL=http://localhost:5173
ENVEOF
  echo -e "${GREEN}✓ backend/.env created${NC}"
fi

# ── CREATE DATA DIR ─────────────────────────────────────────────
mkdir -p backend/data
echo -e "${GREEN}✓ backend/data/ directory ready${NC}"

# ── DONE ────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}✅ Setup complete!${NC}"
echo ""
echo -e "${CYAN}Next steps:${NC}"
echo ""
echo "  1. (Optional) Add your free API keys to: backend/.env"
echo "     - GEMINI_API_KEY  → https://aistudio.google.com/app/apikey"
echo "     - AZURE_SPEECH_KEY→ https://portal.azure.com → Speech → Free F0"
echo ""
echo "  2. Start the backend (Terminal 1):"
echo -e "     ${YELLOW}cd backend && npm run dev${NC}"
echo ""
echo "  3. Start the frontend (Terminal 2):"
echo -e "     ${YELLOW}cd frontend && npm run dev${NC}"
echo ""
echo "  4. Open in Chrome:"
echo -e "     ${CYAN}http://localhost:5173${NC}"
echo ""
echo "  API health check:"
echo -e "     ${CYAN}http://localhost:3001/api/health${NC}"
echo ""
echo -e "${YELLOW}💡 Tip: Use Chrome for full speech recognition support${NC}"
echo ""
